### ISSUE TITLE
Path of URL gets truncated after host/domain part

### ISSUE THREAD

**Issue by sasbibic** [openhab/openhab-android#2504]
### Actual behaviour
Using Web ui 3.0. When  actionURL is defined with path part (https://a.b.c/path), click on link follows only to domain part (https://a.b.c), same UI definition works in browser as expected. Src config field of oh-webframe-card, gets also truncated.

### Expected behaviour
View should follow complete URL with path part.

 
### Steps to reproduce
Example of UI definitions that don't work.

```- component: oh-list-item
      config:
        title: Grafana
        icon: f7:chart_bar_alt_fill
        action: url
        actionUrl: https://somehost/grafana/d/000000001/doma?orgId=1
```
```
component: oh-webframe-card
config:
  style:
    loading: lazy
  height: 400
  src: https://calendar.google.com/calendar/embed?wkst=2&bgcolor=%23ffffff&ctz=Europe%2FBelgrade& ....
```
#### Client
* Android version:  10
* Device model:  xiaomi redmi note 8 pro
* App version: openHAB beta  version 2.16.13-beta
* Build flavor: Full 
* Device language: English 

#### Server
* Server version: openHAB 3.1.0 Build #2279
* Reverse Proxy:  nginx/1.14.2
* Authentication method: SSL Client certificate 

#### openHAB Cloud
*  myopenhab.org: 
* Authentication method: user/password

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>
