### ISSUE TITLE
Using flavor: css-grid, destroys MainUI3 page functionality in AppBrowser

### ISSUE THREAD

**Issue by WhiteSockedDancer** [openhab/openhab-android#2974]
### Actual behaviour
Describe us what happens

I want to use following page in the Android App:

```
config:
  label: Jay
  layoutType: responsive
  order: "1"
  sidebar: true
blocks:
  - component: oh-block
    config: {}
    slots:
      default:
        - component: oh-grid-row
          config: {}
          slots:
            default:
              - component: oh-grid-col
                config: {}
                slots:
                  default:
                    - component: widget:widget_notification_drawer
                      config: {}
masonry:
  - component: oh-masonry
    config:
      flavor: css-grid
    slots:
      default:
        - component: widget:widget_Jay_Mode
          config: {}
        - component: widget:widget_jay_jarvis
          config: {}
        - component: widget:widget_Jay_J1K1
          config: {}
        - component: widget:widget_Jay_J6K6
          config: {}
        - component: widget:widget_Jay_Beamer
          config: {}
        - component: widget:widget_Jay_Rollershutters
          config: {}
        - component: widget:widget_Jay_Bed
          config: {}
        - component: widget:widget_Jay_AVR
          config: {}
        - component: widget:widget_Jay_SyncBox
          config: {}
        - component: widget:widget_jay_sim
          config: {}
        - component: widget:widget_jay_lights
          config: {}
        - component: widget:widget_Jay_Spotify
          config: {}
        - component: oh-toggle-card
          config:
            item: Room_Jay_Profile_AutoOff
            title: Eclipse Auto OFF
grid: null
canvas: null
```

### Expected behaviour
Describe us what should happen

 
### Steps to reproduce
having 
```
    config:
      flavor: css-grid
```
makes the page not functional (due to wrong placements and not working clicks on some elements).
![image](https://user-images.githubusercontent.com/52671054/178476553-23015966-04e2-4c50-92f1-7c8a6767d4ec.png)
![image](https://user-images.githubusercontent.com/52671054/178476497-37ea5f28-48a8-4eb7-8e65-022b7b8fed51.png)

for example the Toggle-knob and range sliders are at the Top of the page.
removing the flavor makes the page useable again. 

### Can you reproduce the issue in demo mode?
didnt try. just went with my workaround and removed the styling.

#### Client
* Android version: 11 (i guess)
* Device model: Samsung Galaxy S20 FE 5G
* App version :  2.20.15-beta
* Build flavor : 
* Device language: German

#### Server
* Server version: openHAB 3.3.0, Release Build, docker
* Reverse Proxy: used (Synology DSM)
* Authentication method : 

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: self-hosted
* openHAB Cloud version : dont know where to check. latest available
* Authentication method :
