### ISSUE TITLE
SVG current color ignored sometimes in Main UI, but not in Desktop browser or sitemaps

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3395]
I have these two icons: 
![office_phone](https://github.com/openhab/openhab-android/assets/4992947/c255a1a6-69c8-44e7-9bd7-92ae30b68cf1)
![lg](https://github.com/openhab/openhab-android/assets/4992947/62679d4d-5b0b-49b1-8157-035cdfe8eda5)

I put them to two items, and they appear in a sitemap.  When openHAB-Android 3.5.2-beta shows them in dark or light mode, the background and foreground colors are shown correctly.

As next I put the same items in Main UI:
```yaml
component: oh-label-card
config:
  icon: office_phone
  item: abc
  title: def

component: oh-label-card
config:
  item: ghi
  icon: lg
  title: jkl
```
I use openHAB 3.4.3.

Firefox does display the icons correctly, when Main UI is in Auto dark mode.  When I change the browser preference to light/dark, the icons are displayed correctly.  In Dark and Light mode Chrome for Windows also displays the icons correctly.

When I load the icons in openHAB-Android, Main UI, dark mode, the lg icon is displayed black foreground on black background.  The office_phone icon is shown in white foreground, black background.  Chrome on the same device displays the icons also correctly, so I guess the problem is not in WebView.

The problem report is that openHAB-Android does not show the lg icon in dark mode in Main UI as
